### ISSUE TITLE
error when using kong 0.14.1

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa-kong-endpoint#6]
getting following error with latest luarocks when running 
```kong migrations up```
```
018/08/27 22:27:09 [info] migrating bcgov-gwa-endpoint for database kong
Error:
.../kong/plugins/bcgov-gwa-endpoint/migrations/postgres.lua:26: attempt to index field 'acls' (a nil value)
stack traceback:
        .../kong/plugins/bcgov-gwa-endpoint/migrations/postgres.lua:26: in function 'up'
        /usr/local/share/lua/5.1/kong/dao/factory.lua:416: in function 'migrate'
        /usr/local/share/lua/5.1/kong/dao/factory.lua:534: in function 'run_migrations'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>
        [C]: in function 'xpcall'
        init_worker_by_lua:55: in function <init_worker_by_lua:53>
```

**Comment by pauldaustin** [comment]
Updated the migrations file to work with 0.14.1. The migrations have a new name, so they will be forced to run. It doesn't matter that the old migrations failed.

Deployed 1.3.1-0 to luarocks

**Comment by ll911** [comment]
```kong migrations up``` success
adding plugin to service/route success

**Comment by ll911** [comment]
gwa 1.2.3-1 admin app still works for kong-0.14.1, however, all gwa created endpoint has groups/acl enabled getting 403 error, e.g.
https://applogs-d.apps.gov.bc.ca/int/cpf/

**Comment by pauldaustin** [comment]
I just confirmed by default when you create an API it didn't enable the acls plugin. If you enabled the acls plugin then you have to make sure there is a group that the user is a member of.

The gwa plugin should auto add an acl for a user using the 'sm_authdirname' header set by the reverse proxy. For example the group idir is created for all internal users.

FYI it would be helpful if you included the full kong configuration of the api and the associated plugins in the error reports.

**Comment by ll911** [comment]
added, same location to get the both json

**Comment by pauldaustin** [comment]
Any chance you can dump the headers that are being sent from the reverse proxy to kong for that request?

**Comment by pauldaustin** [comment]
Just a heads up the Kong API is completely unstable, is under a re-organization and isn't fully documented.

This means what works in one release isn't likely to work in the next until they stabilize at 1.0.0.

I'll have a look at it again tomorrow and see if I can figure out how to get it to work again.

**Comment by ll911** [comment]
K, btw, here is the test url you can check headers https://test.apps.gov.bc.ca/ext/httpbin/headers

**Comment by pauldaustin** [comment]
I have release 1.3.2-0 of the gwa-kong-endpoint plugin.

This version is only valid with Kong 0.14.1.

As the Kong API is still pre 1.0.0 it seems to change every release. Don't upgrade to a new release without fully testing.

**Comment by pauldaustin** [comment]
Actually 1.3.2-1 the other version still had a log statement on every request

**Comment by pauldaustin** [comment]
Try 1.3.2-2

Again this is due to the unstable pre-release kong API's constantly changing

**Comment by pauldaustin** [comment]
Deployed new version.

I keep getting caught out by not merging a pull request. Slightly different workflow from other projects where my repository is the master.

**Comment by ll911** [comment]
1.3.2-3 install success
